### ISSUE TITLE
bootstrap css classes not loaded in mediawiki 1.34 (standalone)

### ISSUE THREAD

**Issue by Extarys** [ProfessionalWiki/Bootstrap#10]
I've installed Mediawiki v1.34. It's running inside a docker container with a volume attached to a folder named `html`.

I created the composer.local.json file as instructed and ran `sudo docker run --rm --interactive --tty --volume $PWD/html:/app composer update`

I've also added the required lines in the LocalSettings.php file.

The page is loading `https://wiki.redacted/load.php?lang=en-ca&modules=ext.bootstrap.styles%7Cmediawiki.legacy.commonPrint%2Cshared%7Cmediawiki.skinning.interface%7Cskins.vector.styles&only=styles&skin=vector` but I cannot find, for example `.alert-success` in the file.

I activated php error reporting and I see no error.

Am I missing something or this is simply not compatible with v1.34?

**Comment by s7eph4n** [comment]
I don't think that `alert-success` is defined in Bootstrap.

**Comment by s7eph4n** [comment]
It seems to work for me. You could try loading `http://...../load.php?lang=en-ca&modules=ext.bootstrap.styles&only=styles&skin=vector&debug=true` and see if there are any errors.

**Comment by JeroenDeDauw** [comment]
@Extarys please let us know if this is still an issue.
