### ISSUE TITLE
Error after Installing

### ISSUE THREAD

**Issue by supercat1510** [ProfessionalWiki/Bootstrap#53]
I install the Package on a new Mediawiki Version and get following Error:

`[YgKCiMBtswvTd6yXl6FSbgAAVyE] /load.php?lang=de&modules=ext.visualEditor.desktopArticleTarget.noscript%7Cmediawiki.ui.button%7Cskins.chameleon%7Czzz.ext.bootstrap.styles&only=styles&skin=chameleon Error: Call to undefined function SCSS\wfMemcKey()

Backtrace:

from /extensions/Bootstrap/SCSS/ResourceLoaderSCSSModule.php(188)
#0 /extensions/Bootstrap/SCSS/ResourceLoaderSCSSModule.php(128): SCSS\ResourceLoaderSCSSModule->getCacheKey(ResourceLoaderContext)
#1 /extensions/Bootstrap/SCSS/ResourceLoaderSCSSModule.php(112): SCSS\ResourceLoaderSCSSModule->retrieveStylesFromCache(ResourceLoaderContext)
#2 /includes/resourceloader/ResourceLoaderModule.php(782): SCSS\ResourceLoaderSCSSModule->getStyles(ResourceLoaderContext)
#3 /includes/resourceloader/ResourceLoaderModule.php(733): ResourceLoaderModule->buildContent(ResourceLoaderContext)
#4 /includes/resourceloader/ResourceLoader.php(1131): ResourceLoaderModule->getModuleContent(ResourceLoaderContext)
#5 /includes/resourceloader/ResourceLoader.php(838): ResourceLoader->makeModuleResponse(ResourceLoaderContext, array, array)
#6 /load.php(51): ResourceLoader->respond(ResourceLoaderContext)
#7 /load.php(38): wfLoadMain()
#8 {main}`

**Comment by malberts** [comment]
How did you install this? Did you use Composer?

**Comment by supercat1510** [comment]
Problem fixed.
The Bootstrap Composer Version was 4.3.4 - i've updated on 4.5.0 and it works.
